name: Run Jest tests

on:
  push:
    branches:
      - main
env:
  DB_URL: ${{secrets.DB_URL}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
jobs:
  jestTest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm i
      - run: npm run test
